// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phonev2.Repository;

#nullable disable

namespace phonev2.Migrations
{
    [DbContext(typeof(PhoneLapDbContext))]
    [Migration("20250706095807_lk")]
    partial class lk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("phonev2.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madichvu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giadichvu");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tendichvu");

                    b.Property<int?>("ThoiGianSua")
                        .HasColumnType("int")
                        .HasColumnName("thoigiansua");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu");

                    b.HasIndex("TrangThai");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.Property<int>("MaLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("malinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLinhKien"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giaban");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gianhap");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hangsanxuat");

                    b.Property<int>("MaLoaiLinhKien")
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("soluongton");

                    b.Property<string>("TenLinhKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenlinhkien");

                    b.Property<string>("ThongSoKyThuat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("thongsoktyhuat");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLinhKien");

                    b.HasIndex("GiaBan");

                    b.HasIndex("HangSanXuat");

                    b.HasIndex("MaLoaiLinhKien");

                    b.HasIndex("NgayTao");

                    b.HasIndex("SoLuongTon");

                    b.HasIndex("TenLinhKien");

                    b.HasIndex("TrangThai");

                    b.ToTable("LinhKien");
                });

            modelBuilder.Entity("phonev2.Models.LoaiLinhKien", b =>
                {
                    b.Property<int>("MaLoaiLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiLinhKien"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenLoaiLinhKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenloailinhkien");

                    b.Property<int?>("ThoiGianBaoHanh")
                        .HasColumnType("int")
                        .HasColumnName("thoigianbaohanh");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLoaiLinhKien");

                    b.HasIndex("TenLoaiLinhKien");

                    b.HasIndex("ThoiGianBaoHanh");

                    b.HasIndex("TrangThai");

                    b.ToTable("LoaiLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.HasOne("phonev2.Models.LoaiLinhKien", "LoaiLinhKien")
                        .WithMany()
                        .HasForeignKey("MaLoaiLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiLinhKien");
                });
#pragma warning restore 612, 618
        }
    }
}
