// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phonev2.Repository;

#nullable disable

namespace phonev2.Migrations
{
    [DbContext(typeof(PhoneLapDbContext))]
    [Migration("20250706122655_nhanvien")]
    partial class nhanvien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("phonev2.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madichvu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giadichvu");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tendichvu");

                    b.Property<int?>("ThoiGianSua")
                        .HasColumnType("int")
                        .HasColumnName("thoigiansua");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu");

                    b.HasIndex("TrangThai");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.Property<int>("MaLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("malinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLinhKien"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giaban");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gianhap");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hangsanxuat");

                    b.Property<int>("MaLoaiLinhKien")
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("soluongton");

                    b.Property<string>("TenLinhKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenlinhkien");

                    b.Property<string>("ThongSoKyThuat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("thongsoktyhuat");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLinhKien");

                    b.HasIndex("GiaBan");

                    b.HasIndex("HangSanXuat");

                    b.HasIndex("MaLoaiLinhKien");

                    b.HasIndex("NgayTao");

                    b.HasIndex("SoLuongTon");

                    b.HasIndex("TenLinhKien");

                    b.HasIndex("TrangThai");

                    b.ToTable("LinhKien");
                });

            modelBuilder.Entity("phonev2.Models.LoaiLinhKien", b =>
                {
                    b.Property<int>("MaLoaiLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiLinhKien"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenLoaiLinhKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenloailinhkien");

                    b.Property<int?>("ThoiGianBaoHanh")
                        .HasColumnType("int")
                        .HasColumnName("thoigianbaohanh");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLoaiLinhKien");

                    b.HasIndex("TenLoaiLinhKien");

                    b.HasIndex("ThoiGianBaoHanh");

                    b.HasIndex("TrangThai");

                    b.ToTable("LoaiLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manhacungcap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tennhacungcap");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai");

                    b.HasIndex("TenNhaCungCap");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("phonev2.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manhanvien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chucvu");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoten");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("luong");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaynghiviec");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaysinh");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayvaolam");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ChucVu");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HoTen");

                    b.HasIndex("NgayNghiViec");

                    b.HasIndex("NgayVaoLam");

                    b.HasIndex("SoDienThoai");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhanVien", t =>
                        {
                            t.HasCheckConstraint("CK_NhanVien_Luong", "Luong >= 0");

                            t.HasCheckConstraint("CK_NhanVien_NgayNghiViec", "NgayNghiViec IS NULL OR NgayNghiViec >= NgayVaoLam");

                            t.HasCheckConstraint("CK_NhanVien_NgaySinh", "NgaySinh <= GETDATE()");

                            t.HasCheckConstraint("CK_NhanVien_NgayVaoLam", "NgayVaoLam >= NgaySinh");
                        });
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.HasOne("phonev2.Models.LoaiLinhKien", "LoaiLinhKien")
                        .WithMany()
                        .HasForeignKey("MaLoaiLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiLinhKien");
                });
#pragma warning restore 612, 618
        }
    }
}
