// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phonev2.Repository;

#nullable disable

namespace phonev2.Migrations
{
    [DbContext(typeof(PhoneLapDbContext))]
    [Migration("20250722005223_dbcontext")]
    partial class dbcontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("phonev2.Models.ChiTietLinhKien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaLinhKien")
                        .HasColumnType("int")
                        .HasColumnName("malinhkien");

                    b.Property<int>("MaPhieuSua")
                        .HasColumnType("int")
                        .HasColumnName("maphieusua");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("soluong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanhtien");

                    b.HasKey("Id");

                    b.HasIndex("MaLinhKien");

                    b.HasIndex("MaPhieuSua");

                    b.ToTable("ChiTietLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("maphieunhap");

                    b.Property<int>("MaLinhKien")
                        .HasColumnType("int")
                        .HasColumnName("malinhkien");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghichu");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gianhap");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanhtien");

                    b.HasKey("MaPhieuNhap", "MaLinhKien");

                    b.HasIndex("MaLinhKien");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("ChiTietPhieuNhap", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietPhieuNhap_GiaNhap", "GiaNhap >= 0");

                            t.HasCheckConstraint("CK_ChiTietPhieuNhap_SoLuong", "SoLuong > 0");

                            t.HasCheckConstraint("CK_ChiTietPhieuNhap_ThanhTien", "ThanhTien >= 0");
                        });
                });

            modelBuilder.Entity("phonev2.Models.ChiTietPhieuSua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("madichvu");

                    b.Property<int>("MaPhieuSua")
                        .HasColumnType("int")
                        .HasColumnName("maphieusua");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("soluong");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanhtien");

                    b.HasKey("Id");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaPhieuSua");

                    b.ToTable("ChiTietPhieuSua");
                });

            modelBuilder.Entity("phonev2.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madichvu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit")
                        .HasColumnName("daxoa");

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giadichvu");

                    b.Property<string>("LyDoXoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("lydoxoa");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayxoa");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tendichvu");

                    b.Property<int?>("ThoiGianSua")
                        .HasColumnType("int")
                        .HasColumnName("thoigiansua");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaDichVu");

                    b.HasIndex("TenDichVu");

                    b.HasIndex("TrangThai");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("phonev2.Models.DichVuLinhKien", b =>
                {
                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaLinhKien")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDichVu", "MaLinhKien");

                    b.HasIndex("MaLinhKien");

                    b.ToTable("DichVuLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("makhachhang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoten");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<decimal>("TongChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tongchitieu");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("HoTen");

                    b.HasIndex("NgayTao");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TongChiTieu");

                    b.HasIndex("TrangThai");

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KhachHang_NgayTao", "NgayTao <= GETDATE()");

                            t.HasCheckConstraint("CK_KhachHang_TongChiTieu", "TongChiTieu >= 0");
                        });
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.Property<int>("MaLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("malinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLinhKien"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit")
                        .HasColumnName("daxoa");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giaban");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gianhap");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hangsanxuat");

                    b.Property<string>("LyDoXoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("lydoxoa");

                    b.Property<int>("MaLoaiLinhKien")
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayxoa");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("soluongton");

                    b.Property<string>("TenLinhKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenlinhkien");

                    b.Property<string>("ThongSoKyThuat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("thongsoktyhuat");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLinhKien");

                    b.HasIndex("GiaBan");

                    b.HasIndex("HangSanXuat");

                    b.HasIndex("MaLoaiLinhKien");

                    b.HasIndex("NgayTao");

                    b.HasIndex("SoLuongTon");

                    b.HasIndex("TenLinhKien");

                    b.HasIndex("TrangThai");

                    b.ToTable("LinhKien");
                });

            modelBuilder.Entity("phonev2.Models.LoaiLinhKien", b =>
                {
                    b.Property<int>("MaLoaiLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maloailinhkien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiLinhKien"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenLoaiLinhKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenloailinhkien");

                    b.Property<int?>("ThoiGianBaoHanh")
                        .HasColumnType("int")
                        .HasColumnName("thoigianbaohanh");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaLoaiLinhKien");

                    b.HasIndex("TenLoaiLinhKien");

                    b.HasIndex("ThoiGianBaoHanh");

                    b.HasIndex("TrangThai");

                    b.ToTable("LoaiLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manhacungcap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tennhacungcap");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaNhaCungCap");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai");

                    b.HasIndex("TenNhaCungCap");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("phonev2.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manhanvien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chucvu");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoten");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("luong");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaynghiviec");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaysinh");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayvaolam");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangthai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ChucVu");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HoTen");

                    b.HasIndex("NgayNghiViec");

                    b.HasIndex("NgayVaoLam");

                    b.HasIndex("SoDienThoai");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhanVien", t =>
                        {
                            t.HasCheckConstraint("CK_NhanVien_Luong", "Luong >= 0");

                            t.HasCheckConstraint("CK_NhanVien_NgayNghiViec", "NgayNghiViec IS NULL OR NgayNghiViec >= NgayVaoLam");

                            t.HasCheckConstraint("CK_NhanVien_NgaySinh", "NgaySinh <= GETDATE()");

                            t.HasCheckConstraint("CK_NhanVien_NgayVaoLam", "NgayVaoLam >= NgaySinh");
                        });
                });

            modelBuilder.Entity("phonev2.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maphieunhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ghichu");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("manhacungcap");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("manhanvien");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaycapnhat");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaynhap");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tongtien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Nháp")
                        .HasColumnName("trangthai");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayNhap");

                    b.HasIndex("NgayTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("PhieuNhap", t =>
                        {
                            t.HasCheckConstraint("CK_PhieuNhap_NgayNhap", "NgayNhap <= GETDATE()");

                            t.HasCheckConstraint("CK_PhieuNhap_TongTien", "TongTien >= 0");

                            t.HasCheckConstraint("CK_PhieuNhap_TrangThai", "TrangThai IN ('Nháp', 'Đã xác nhận')");
                        });
                });

            modelBuilder.Entity("phonev2.Models.PhieuSua", b =>
                {
                    b.Property<int>("MaPhieuSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maphieusua");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuSua"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ghichu");

                    b.Property<TimeSpan?>("GioHoanThanh")
                        .HasColumnType("time")
                        .HasColumnName("giokhoanthanhtacvu");

                    b.Property<int?>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("makhachhang");

                    b.Property<int?>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("manhanvien");

                    b.Property<DateTime?>("NgayGioHoanThanh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaygiohoanthanhtacvu");

                    b.Property<DateTime?>("NgayHenTra")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayhentra");

                    b.Property<DateTime>("NgaySua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaysua")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaytrathucte");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tongtien");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("trangthai");

                    b.HasKey("MaPhieuSua");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayHenTra");

                    b.HasIndex("NgaySua");

                    b.HasIndex("NgayTraThucTe");

                    b.HasIndex("TrangThai");

                    b.ToTable("PhieuSua");
                });

            modelBuilder.Entity("phonev2.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mathietbi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hangsanxuat");

                    b.Property<string>("LoaiThietBi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaithietbi");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("makhachhang");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenthietbi");

                    b.HasKey("MaThietBi");

                    b.HasIndex("HangSanXuat");

                    b.HasIndex("LoaiThietBi");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("Model");

                    b.HasIndex("TenThietBi");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("phonev2.Models.ChiTietLinhKien", b =>
                {
                    b.HasOne("phonev2.Models.LinhKien", "LinhKien")
                        .WithMany()
                        .HasForeignKey("MaLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phonev2.Models.PhieuSua", "PhieuSua")
                        .WithMany("ChiTietLinhKiens")
                        .HasForeignKey("MaPhieuSua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhKien");

                    b.Navigation("PhieuSua");
                });

            modelBuilder.Entity("phonev2.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("phonev2.Models.LinhKien", "LinhKien")
                        .WithMany()
                        .HasForeignKey("MaLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phonev2.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhKien");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("phonev2.Models.ChiTietPhieuSua", b =>
                {
                    b.HasOne("phonev2.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phonev2.Models.PhieuSua", "PhieuSua")
                        .WithMany("ChiTietPhieuSuas")
                        .HasForeignKey("MaPhieuSua")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("PhieuSua");
                });

            modelBuilder.Entity("phonev2.Models.DichVuLinhKien", b =>
                {
                    b.HasOne("phonev2.Models.DichVu", "DichVu")
                        .WithMany("DichVuLinhKiens")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phonev2.Models.LinhKien", "LinhKien")
                        .WithMany("DichVuLinhKiens")
                        .HasForeignKey("MaLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("LinhKien");
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.HasOne("phonev2.Models.LoaiLinhKien", "LoaiLinhKien")
                        .WithMany()
                        .HasForeignKey("MaLoaiLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiLinhKien");
                });

            modelBuilder.Entity("phonev2.Models.PhieuNhap", b =>
                {
                    b.HasOne("phonev2.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phonev2.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("phonev2.Models.PhieuSua", b =>
                {
                    b.HasOne("phonev2.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("phonev2.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("phonev2.Models.ThietBi", b =>
                {
                    b.HasOne("phonev2.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("phonev2.Models.DichVu", b =>
                {
                    b.Navigation("DichVuLinhKiens");
                });

            modelBuilder.Entity("phonev2.Models.LinhKien", b =>
                {
                    b.Navigation("DichVuLinhKiens");
                });

            modelBuilder.Entity("phonev2.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("phonev2.Models.PhieuSua", b =>
                {
                    b.Navigation("ChiTietLinhKiens");

                    b.Navigation("ChiTietPhieuSuas");
                });
#pragma warning restore 612, 618
        }
    }
}
